# Generated by Django 4.1 on 2022-08-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadfiles_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('upfile', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
