# Generated by Django 4.1 on 2022-08-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloadfiles_app', '0002_upfile_delete_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upfile',
            old_name='upfile',
            new_name='upload',
        ),
    ]
